name: Merge to main workflows

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
    # checkout to the commit that has been pushed
    - uses: actions/checkout@v4
      with:
          submodules: true
          fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3.0.0
      with:
        hugo-version: 'latest'
        extended: true

    # - name: Update Hugo Modules
    #   run: hugo mod tidy

    - name: Update Hugo Modules
      run: hugo mod clean

    # - name: Setup Node
    #   uses: actions/setup-node@v4
    #   with:
    #     node-version: 18

    # - name: Install node modules
    #   run: |
    #     hugo mod npm pack
    #     npm install

    - uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        # The action defaults to search for the dependency file (package-lock.json,
        # npm-shrinkwrap.json or yarn.lock) in the repository root, and uses its
        # hash as a part of the cache key.
        # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
        cache-dependency-path: '**/package-lock.json'

    - run: npm ci

    - name: Build
      run: hugo --minify

    # push the generated content into the `gh-pages` branch.
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public
        cname: laminscreativestudio.com
